version: '3'
services:

  deakin-library:
    image: deakin-library
    build: 
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: deakin-library
    ports:
     - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgresql://sit722part4_user:4G8gGGznDS7nL8I97VmTbNxL4KoepQzO@dpg-crbpgodsvqrc73f377vg-a.oregon-postgres.render.com/sit722part4
    restart: "no"

  deakin-inventory:
    image: deakin-inventory
    build: 
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: deakin-inventory
    ports:
     - "5000:5000"
    environment:
      - PORT=5000
      - DATABASE_URL=postgresql://sit722part4_user:4G8gGGznDS7nL8I97VmTbNxL4KoepQzO@dpg-crbpgodsvqrc73f377vg-a.oregon-postgres.render.com/sit722part4
    restart: "no"
